# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DoubleSlit1D.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 672)
        MainWindow.setMinimumSize(QtCore.QSize(780, 0))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gb_exp = QtWidgets.QGroupBox(self.centralWidget)
        self.gb_exp.setObjectName("gb_exp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_exp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_imtool = QtWidgets.QPushButton(self.gb_exp)
        self.bt_imtool.setObjectName("bt_imtool")
        self.verticalLayout_2.addWidget(self.bt_imtool)
        self.button_data = QtWidgets.QPushButton(self.gb_exp)
        self.button_data.setObjectName("button_data")
        self.verticalLayout_2.addWidget(self.button_data)
        self.horizontalLayout.addWidget(self.gb_exp)
        self.gb_sim = QtWidgets.QGroupBox(self.centralWidget)
        self.gb_sim.setEnabled(False)
        self.gb_sim.setCheckable(False)
        self.gb_sim.setChecked(False)
        self.gb_sim.setObjectName("gb_sim")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gb_sim)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SpinBox_b = QtWidgets.QDoubleSpinBox(self.gb_sim)
        self.SpinBox_b.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_b.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_b.setDecimals(0)
        self.SpinBox_b.setMinimum(10.0)
        self.SpinBox_b.setMaximum(1000.0)
        self.SpinBox_b.setSingleStep(1.0)
        self.SpinBox_b.setProperty("value", 435.0)
        self.SpinBox_b.setObjectName("SpinBox_b")
        self.gridLayout_3.addWidget(self.SpinBox_b, 1, 3, 1, 1)
        self.Internal_Spot = QtWidgets.QLineEdit(self.gb_sim)
        self.Internal_Spot.setObjectName("Internal_Spot")
        self.gridLayout_3.addWidget(self.Internal_Spot, 3, 5, 1, 1)
        self.label_b = QtWidgets.QLabel(self.gb_sim)
        self.label_b.setObjectName("label_b")
        self.gridLayout_3.addWidget(self.label_b, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gb_sim)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 6, 1, 1)
        self.slider_a = QtWidgets.QSlider(self.gb_sim)
        self.slider_a.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_a.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_a.setMinimum(1)
        self.slider_a.setMaximum(300)
        self.slider_a.setSingleStep(1)
        self.slider_a.setPageStep(100)
        self.slider_a.setProperty("value", 100)
        self.slider_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_a.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_a.setTickInterval(20)
        self.slider_a.setObjectName("slider_a")
        self.gridLayout_3.addWidget(self.slider_a, 0, 7, 1, 1)
        self.Central_Spot = QtWidgets.QLineEdit(self.gb_sim)
        self.Central_Spot.setMinimumSize(QtCore.QSize(0, 20))
        self.Central_Spot.setObjectName("Central_Spot")
        self.gridLayout_3.addWidget(self.Central_Spot, 3, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gb_sim)
        self.label_4.setMinimumSize(QtCore.QSize(0, 13))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 5, 1, 1)
        self.SpinBox_lambda = QtWidgets.QSpinBox(self.gb_sim)
        self.SpinBox_lambda.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_lambda.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_lambda.setMinimum(500)
        self.SpinBox_lambda.setMaximum(700)
        self.SpinBox_lambda.setSingleStep(1)
        self.SpinBox_lambda.setProperty("value", 632)
        self.SpinBox_lambda.setObjectName("SpinBox_lambda")
        self.gridLayout_3.addWidget(self.SpinBox_lambda, 1, 1, 1, 1)
        self.slider_D = QtWidgets.QSlider(self.gb_sim)
        self.slider_D.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_D.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_D.setMinimum(10)
        self.slider_D.setMaximum(300)
        self.slider_D.setSingleStep(1)
        self.slider_D.setProperty("value", 60)
        self.slider_D.setSliderPosition(60)
        self.slider_D.setOrientation(QtCore.Qt.Horizontal)
        self.slider_D.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_D.setTickInterval(50)
        self.slider_D.setObjectName("slider_D")
        self.gridLayout_3.addWidget(self.slider_D, 2, 3, 1, 1)
        self.label_lamda = QtWidgets.QLabel(self.gb_sim)
        self.label_lamda.setObjectName("label_lamda")
        self.gridLayout_3.addWidget(self.label_lamda, 0, 0, 1, 1)
        self.label_f2 = QtWidgets.QLabel(self.gb_sim)
        self.label_f2.setObjectName("label_f2")
        self.gridLayout_3.addWidget(self.label_f2, 2, 2, 1, 1)
        self.SpinBox_D = QtWidgets.QDoubleSpinBox(self.gb_sim)
        self.SpinBox_D.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_D.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_D.setDecimals(1)
        self.SpinBox_D.setMinimum(1.0)
        self.SpinBox_D.setMaximum(30.0)
        self.SpinBox_D.setSingleStep(0.1)
        self.SpinBox_D.setProperty("value", 6.0)
        self.SpinBox_D.setObjectName("SpinBox_D")
        self.gridLayout_3.addWidget(self.SpinBox_D, 3, 3, 1, 1)
        self.SpinBox_db = QtWidgets.QDoubleSpinBox(self.gb_sim)
        self.SpinBox_db.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_db.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_db.setDecimals(1)
        self.SpinBox_db.setMinimum(0.0)
        self.SpinBox_db.setMaximum(500.0)
        self.SpinBox_db.setSingleStep(10.0)
        self.SpinBox_db.setProperty("value", 0.0)
        self.SpinBox_db.setObjectName("SpinBox_db")
        self.gridLayout_3.addWidget(self.SpinBox_db, 1, 5, 1, 1)
        self.slider_db = QtWidgets.QSlider(self.gb_sim)
        self.slider_db.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_db.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_db.setMaximum(500)
        self.slider_db.setSingleStep(10)
        self.slider_db.setProperty("value", 0)
        self.slider_db.setOrientation(QtCore.Qt.Horizontal)
        self.slider_db.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_db.setTickInterval(50)
        self.slider_db.setObjectName("slider_db")
        self.gridLayout_3.addWidget(self.slider_db, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.gb_sim)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 4, 1, 1)
        self.slider_b = QtWidgets.QSlider(self.gb_sim)
        self.slider_b.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_b.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_b.setMinimum(10)
        self.slider_b.setMaximum(600)
        self.slider_b.setSingleStep(1)
        self.slider_b.setPageStep(100)
        self.slider_b.setProperty("value", 435)
        self.slider_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_b.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_b.setTickInterval(50)
        self.slider_b.setObjectName("slider_b")
        self.gridLayout_3.addWidget(self.slider_b, 0, 3, 1, 1)
        self.slider_lambda = QtWidgets.QSlider(self.gb_sim)
        self.slider_lambda.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_lambda.setStyleSheet("font: 12pt \"Helvetica\";")
        self.slider_lambda.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_lambda.setMinimum(500)
        self.slider_lambda.setMaximum(700)
        self.slider_lambda.setSingleStep(1)
        self.slider_lambda.setProperty("value", 632)
        self.slider_lambda.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lambda.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_lambda.setTickInterval(50)
        self.slider_lambda.setObjectName("slider_lambda")
        self.gridLayout_3.addWidget(self.slider_lambda, 0, 1, 1, 1)
        self.SpinBox_a = QtWidgets.QDoubleSpinBox(self.gb_sim)
        self.SpinBox_a.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_a.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_a.setDecimals(3)
        self.SpinBox_a.setMinimum(0.001)
        self.SpinBox_a.setMaximum(1.0)
        self.SpinBox_a.setSingleStep(0.001)
        self.SpinBox_a.setProperty("value", 0.1)
        self.SpinBox_a.setObjectName("SpinBox_a")
        self.gridLayout_3.addWidget(self.SpinBox_a, 1, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gb_sim)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 6, 1, 1)
        self.slider_sx = QtWidgets.QSlider(self.gb_sim)
        self.slider_sx.setMinimum(10)
        self.slider_sx.setMaximum(400)
        self.slider_sx.setSingleStep(1)
        self.slider_sx.setProperty("value", 50)
        self.slider_sx.setOrientation(QtCore.Qt.Horizontal)
        self.slider_sx.setObjectName("slider_sx")
        self.gridLayout_3.addWidget(self.slider_sx, 2, 1, 1, 1)
        self.SpinBox_sx = QtWidgets.QDoubleSpinBox(self.gb_sim)
        self.SpinBox_sx.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_sx.setDecimals(1)
        self.SpinBox_sx.setMinimum(1.0)
        self.SpinBox_sx.setMaximum(40.0)
        self.SpinBox_sx.setSingleStep(0.1)
        self.SpinBox_sx.setProperty("value", 5.0)
        self.SpinBox_sx.setObjectName("SpinBox_sx")
        self.gridLayout_3.addWidget(self.SpinBox_sx, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gb_sim)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout.addWidget(self.gb_sim)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.mplwidget1D = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget1D.setObjectName("mplwidget1D")
        self.verticalLayout_3.addWidget(self.mplwidget1D)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 870, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diffraction - Fraunhofer"))
        self.gb_exp.setTitle(_translate("MainWindow", "Experiment"))
        self.bt_imtool.setText(_translate("MainWindow", "Image Tool"))
        self.button_data.setText(_translate("MainWindow", "load profile"))
        self.gb_sim.setTitle(_translate("MainWindow", "Simulation"))
        self.SpinBox_b.setStatusTip(_translate("MainWindow", "Change the width of the rectangular aperture"))
        self.label_b.setText(_translate("MainWindow", "<html><head/><body><p>b1( &mu;m)</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">a(cm)</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Internal Spot (cm)</span></p></body></html>"))
        self.SpinBox_lambda.setStatusTip(_translate("MainWindow", "Change the wave length of monochromatic light"))
        self.slider_D.setStatusTip(_translate("MainWindow", "Change the focal length f2 of the lens L2"))
        self.label_lamda.setText(_translate("MainWindow", "Wavelength(nm)"))
        self.label_f2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">D(m)</p></body></html>"))
        self.SpinBox_D.setStatusTip(_translate("MainWindow", "Change the focal length f2 of the lens L2"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>&Delta;b( &mu;m)</p></body></html>"))
        self.slider_b.setStatusTip(_translate("MainWindow", "Change the width of the rectangular aperture"))
        self.slider_lambda.setStatusTip(_translate("MainWindow", "Change the wave length of monochromatic light"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Central spot (cm)</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "screen dimension (cm)"))

from mplwidget import MPL_WIDGET_2D

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

