# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ImDiffract.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1077, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_load = QtWidgets.QPushButton(self.centralwidget)
        self.bt_load.setObjectName("bt_load")
        self.horizontalLayout_2.addWidget(self.bt_load)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_angle = QtWidgets.QLabel(self.groupBox)
        self.label_angle.setObjectName("label_angle")
        self.verticalLayout.addWidget(self.label_angle)
        self.angle = QtWidgets.QDial(self.groupBox)
        self.angle.setMaximumSize(QtCore.QSize(167772, 167772))
        self.angle.setMinimum(-100)
        self.angle.setMaximum(100)
        self.angle.setSingleStep(1)
        self.angle.setPageStep(50)
        self.angle.setInvertedAppearance(False)
        self.angle.setWrapping(False)
        self.angle.setNotchesVisible(True)
        self.angle.setObjectName("angle")
        self.verticalLayout.addWidget(self.angle)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 3, 1)
        self.label_yc = QtWidgets.QLabel(self.groupBox)
        self.label_yc.setObjectName("label_yc")
        self.gridLayout.addWidget(self.label_yc, 1, 2, 1, 1)
        self.cb_RGB = QtWidgets.QCheckBox(self.groupBox)
        self.cb_RGB.setObjectName("cb_RGB")
        self.gridLayout.addWidget(self.cb_RGB, 0, 4, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ycVal = QtWidgets.QLabel(self.groupBox)
        self.label_ycVal.setTextFormat(QtCore.Qt.RichText)
        self.label_ycVal.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ycVal.setObjectName("label_ycVal")
        self.verticalLayout_2.addWidget(self.label_ycVal)
        self.slider_yc = QtWidgets.QSlider(self.groupBox)
        self.slider_yc.setMinimum(100)
        self.slider_yc.setMaximum(400)
        self.slider_yc.setProperty("value", 100)
        self.slider_yc.setOrientation(QtCore.Qt.Horizontal)
        self.slider_yc.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_yc.setObjectName("slider_yc")
        self.verticalLayout_2.addWidget(self.slider_yc)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 3, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.bt_save = QtWidgets.QPushButton(self.centralwidget)
        self.bt_save.setEnabled(False)
        self.bt_save.setObjectName("bt_save")
        self.horizontalLayout_2.addWidget(self.bt_save)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gv1 = MPL_WIDGET_2D(self.centralwidget)
        self.gv1.setObjectName("gv1")
        self.horizontalLayout.addWidget(self.gv1)
        self.gv2 = MPL_WIDGET_2D(self.centralwidget)
        self.gv2.setObjectName("gv2")
        self.horizontalLayout.addWidget(self.gv2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Tool - ALSO"))
        self.bt_load.setText(_translate("MainWindow", "load image"))
        self.groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.label_angle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\"/></p></body></html>"))
        self.label_yc.setText(_translate("MainWindow", "Y Cursor (pixel)"))
        self.cb_RGB.setText(_translate("MainWindow", "RGB profile"))
        self.label_ycVal.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Image angle"))
        self.bt_save.setText(_translate("MainWindow", "save profile"))

from mplwidget import MPL_WIDGET_2D

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

